# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pas_manager.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import DB_Tools

class Ui_MainWindow(object):
    def refresh(self):
        data = DB_Tools.db_getAll()
        rows = len(data)
        print (data)
        self.dataWid.setRowCount(0);
        _translate = QtCore.QCoreApplication.translate

        self.dataWid.setRowCount(rows);

        for i in range(rows):
            item = QtWidgets.QTableWidgetItem()
            self.dataWid.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.dataWid.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.dataWid.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.dataWid.setItem(i, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.dataWid.setItem(i, 4, item)

            item = self.dataWid.item(i, 0)
            item.setText(_translate("MainWindow", str(data[i][0])))
            item = self.dataWid.item(i, 1)
            item.setText(_translate("MainWindow", data[i][1]))
            item = self.dataWid.item(i, 2)
            item.setText(_translate("MainWindow", data[i][2]))
            item = self.dataWid.item(i, 3)
            item.setText(_translate("MainWindow", data[i][3]))
            item = self.dataWid.item(i, 4)
            item.setText(_translate("MainWindow", data[i][4]))


    def add_pas(self):
        self.tmp_name = self.add_name.text()
        self.tmp_email = self.add_email.text()
        self.tmp_username = self.add_username.text()
        self.tmp_password = self.add_password.text()
        print("Adding [{},{},{},{}]".format(self.tmp_name,self.tmp_email,self.tmp_username,self.tmp_password))\

        if(DB_Tools.Tools.isEmail(self.tmp_email)):
            pass
        else:
            self.tmp_warning = True;

        try:
            DB_Tools.db_insert(self.tmp_name,self.tmp_email,self.tmp_username,self.tmp_password)
        except:
            self.add_msg.setText("Error: Couldn\'t add Password!!")

        if self.tmp_warning:
            self.add_msg.setText("Warning: the Email format incorrect !!")
        else:
            self.add_msg.setText("Password added Successfully !!")
        self.refresh()

    def edit_pas(self):
        self.tmp_id = self.edit_id.text()
        self.tmp_name = self.edit_name.text()
        self.tmp_email = self.edit_email.text()
        self.tmp_username = self.edit_username.text()
        self.tmp_password = self.edit_password.text()
        print("Editing [{},{},{},{},{}]".format(self.tmp_id,self.tmp_name, self.tmp_email, self.tmp_username, self.tmp_password))
        if (DB_Tools.db_getByID(self.tmp_id) == []):
            self.edit_msg.setText("Error: No Such ID !!")
        else:
            try:
                if self.tmp_name != "":
                    DB_Tools.db_update(self.tmp_id , 'Name',self.tmp_name)
                if self.tmp_email != "":
                    DB_Tools.db_update(self.tmp_id , 'Email',self.tmp_email)
                if self.tmp_username != "":
                    DB_Tools.db_update(self.tmp_id , 'Username',self.tmp_username)
                if self.tmp_password != "":
                    DB_Tools.db_update(self.tmp_id , 'Password',self.tmp_password)
            except:
                self.edit_msg.setText("Error: Couldn\'t Edit Password!!")
            self.add_msg.setText("Password updated Successfully !!")
            self.refresh()

    def remove_pas(self):
        self.tmp_id = self.remove_id.text()
        print('Removing {}'.format(self.tmp_id))
        if (DB_Tools.db_getByID(self.tmp_id) == []):
            self.remove_msg.setText("Error: No Such ID !!")
        else:
            try:
                DB_Tools.db_remove(self.tmp_id)
            except:
                self.remove_msg.setText("Error: Couldn\'t Remove Password!!")
        self.add_msg.setText("Password removed Successfully !!")
        self.refresh()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 743)
        MainWindow.setMinimumSize(QtCore.QSize(951, 743))
        MainWindow.setMaximumSize(QtCore.QSize(951, 743))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataWid = QtWidgets.QTableWidget(self.centralwidget)
        self.dataWid.setObjectName("dataWid")
        self.dataWid.setColumnCount(5)
        self.dataWid.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dataWid.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataWid.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataWid.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataWid.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataWid.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.dataWid)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:red")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(33, 24))
        self.label_2.setMaximumSize(QtCore.QSize(33, 24))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.add_name = QtWidgets.QLineEdit(self.centralwidget)
        self.add_name.setMinimumSize(QtCore.QSize(423, 24))
        self.add_name.setMaximumSize(QtCore.QSize(423, 24))
        self.add_name.setObjectName("add_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.add_name)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(31, 24))
        self.label_3.setMaximumSize(QtCore.QSize(31, 24))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.add_email = QtWidgets.QLineEdit(self.centralwidget)
        self.add_email.setMinimumSize(QtCore.QSize(423, 24))
        self.add_email.setMaximumSize(QtCore.QSize(423, 24))
        self.add_email.setObjectName("add_email")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.add_email)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(58, 24))
        self.label_4.setMaximumSize(QtCore.QSize(58, 24))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.add_username = QtWidgets.QLineEdit(self.centralwidget)
        self.add_username.setMinimumSize(QtCore.QSize(423, 24))
        self.add_username.setMaximumSize(QtCore.QSize(423, 24))
        self.add_username.setObjectName("add_username")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.add_username)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(55, 24))
        self.label_5.setMaximumSize(QtCore.QSize(55, 24))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.add_password = QtWidgets.QLineEdit(self.centralwidget)
        self.add_password.setMinimumSize(QtCore.QSize(423, 24))
        self.add_password.setMaximumSize(QtCore.QSize(423, 24))
        self.add_password.setObjectName("add_password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.add_password)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setMinimumSize(QtCore.QSize(423, 24))
        self.add_button.setMaximumSize(QtCore.QSize(423, 24))
        self.add_button.setObjectName("add_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.add_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.add_msg = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_msg.setFont(font)
        self.add_msg.setStyleSheet("color:green")
        self.add_msg.setObjectName("add_msg")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.add_msg)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:red")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMinimumSize(QtCore.QSize(12, 24))
        self.label_11.setMaximumSize(QtCore.QSize(12, 24))
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.edit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_id.setMinimumSize(QtCore.QSize(423, 24))
        self.edit_id.setMaximumSize(QtCore.QSize(423, 24))
        self.edit_id.setObjectName("edit_id")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_id)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(33, 24))
        self.label_7.setMaximumSize(QtCore.QSize(33, 24))
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.edit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_name.setMinimumSize(QtCore.QSize(423, 24))
        self.edit_name.setMaximumSize(QtCore.QSize(423, 24))
        self.edit_name.setObjectName("edit_name")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_name)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(31, 24))
        self.label_8.setMaximumSize(QtCore.QSize(31, 24))
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.edit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_email.setMinimumSize(QtCore.QSize(423, 24))
        self.edit_email.setMaximumSize(QtCore.QSize(423, 24))
        self.edit_email.setObjectName("edit_email")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_email)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(58, 24))
        self.label_9.setMaximumSize(QtCore.QSize(58, 24))
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.edit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_username.setMinimumSize(QtCore.QSize(423, 24))
        self.edit_username.setMaximumSize(QtCore.QSize(423, 24))
        self.edit_username.setObjectName("edit_username")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit_username)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMinimumSize(QtCore.QSize(55, 24))
        self.label_10.setMaximumSize(QtCore.QSize(55, 24))
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.edit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_password.setMinimumSize(QtCore.QSize(423, 24))
        self.edit_password.setMaximumSize(QtCore.QSize(423, 24))
        self.edit_password.setObjectName("edit_password")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_password)
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setMinimumSize(QtCore.QSize(423, 24))
        self.update_button.setMaximumSize(QtCore.QSize(423, 24))
        self.update_button.setObjectName("update_button")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.update_button)
        self.edit_msg = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_msg.setFont(font)
        self.edit_msg.setStyleSheet("color:green")
        self.edit_msg.setObjectName("edit_msg")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.edit_msg)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout.addLayout(self.formLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:red")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(58, 24))
        self.label_13.setMaximumSize(QtCore.QSize(58, 24))
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.remove_id = QtWidgets.QLineEdit(self.centralwidget)
        self.remove_id.setMinimumSize(QtCore.QSize(423, 24))
        self.remove_id.setMaximumSize(QtCore.QSize(423, 24))
        self.remove_id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.remove_id.setObjectName("remove_id")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remove_id)
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setMinimumSize(QtCore.QSize(423, 24))
        self.remove_button.setMaximumSize(QtCore.QSize(423, 24))
        self.remove_button.setObjectName("remove_button")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.remove_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.remove_msg = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.remove_msg.setFont(font)
        self.remove_msg.setStyleSheet("color:green")
        self.remove_msg.setObjectName("remove_msg")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.remove_msg)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_button.clicked.connect(self.add_pas)
        self.update_button.clicked.connect(self.edit_pas)
        self.remove_button.clicked.connect(self.remove_pas)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.dataWid.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.dataWid.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.dataWid.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Username"))
        item = self.dataWid.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.dataWid.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Add Password"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.add_msg.setText(_translate("MainWindow", "Insert a New Password"))
        self.label_6.setText(_translate("MainWindow", "Update Password"))
        self.label_11.setText(_translate("MainWindow", "ID"))
        self.label_7.setText(_translate("MainWindow", "Name"))
        self.label_8.setText(_translate("MainWindow", "Email"))
        self.label_9.setText(_translate("MainWindow", "Username"))
        self.label_10.setText(_translate("MainWindow", "Password"))
        self.update_button.setText(_translate("MainWindow", "Update"))
        self.edit_msg.setText(_translate("MainWindow", "Edit an existing Password"))
        self.label_12.setText(_translate("MainWindow", "Remove Password"))
        self.label_13.setText(_translate("MainWindow", "ID"))
        self.remove_button.setText(_translate("MainWindow", "Remove"))
        self.remove_msg.setText(_translate("MainWindow", "Remove a Password"))
        self.refresh()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())